import type { Lead, ConversationWithLead } from '@/types'

const DEMO_TENANT_ID = 'demo-tenant-id'

export const demoLeads: Lead[] = [
  {
    id: 'demo-lead-1',
    tenantId: DEMO_TENANT_ID,
    name: 'Maria Silva',
    phone: '+5511999887766',
    instagramId: null,
    email: 'maria@email.com',
    avatarUrl: null,
    channel: 'whatsapp',
    source: 'google_ads',
    utmSource: 'google',
    utmMedium: 'cpc',
    utmCampaign: 'verao_2025',
    stage: 'qualifying',
    score: 45,
    tags: ['interessada', 'google'],
    assignedTo: null,
    activeCampaignId: null,
    firstContactAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    lastContactAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    lastMessageAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    convertedAt: null,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-lead-2',
    tenantId: DEMO_TENANT_ID,
    name: 'João Santos',
    phone: '+5511988776655',
    instagramId: null,
    email: null,
    avatarUrl: null,
    channel: 'whatsapp',
    source: 'instagram_ads',
    utmSource: 'instagram',
    utmMedium: 'social',
    utmCampaign: null,
    stage: 'hot',
    score: 72,
    tags: ['quente', 'preço'],
    assignedTo: null,
    activeCampaignId: null,
    firstContactAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    lastContactAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    lastMessageAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    convertedAt: null,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-lead-3',
    tenantId: DEMO_TENANT_ID,
    name: 'Ana Oliveira',
    phone: '+5521977665544',
    instagramId: null,
    email: 'ana.oliveira@gmail.com',
    avatarUrl: null,
    channel: 'whatsapp',
    source: 'organico',
    utmSource: null,
    utmMedium: null,
    utmCampaign: null,
    stage: 'new',
    score: 10,
    tags: [],
    assignedTo: null,
    activeCampaignId: null,
    firstContactAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    lastContactAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    lastMessageAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    convertedAt: null,
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
]

export const demoConversations: ConversationWithLead[] = [
  {
    id: 'demo-conv-1',
    tenantId: DEMO_TENANT_ID,
    leadId: 'demo-lead-1',
    channel: 'whatsapp',
    status: 'ai',
    assignedAgentId: null,
    campaignId: null,
    aiMessagesCount: 3,
    humanMessagesCount: 0,
    leadMessagesCount: 4,
    firstResponseTimeMs: 1200,
    aiModel: 'claude-sonnet-4-20250514',
    aiSummary: 'Lead perguntou sobre preços e horários de atendimento.',
    handoffReason: null,
    handoffAt: null,
    openedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    closedAt: null,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    leadName: 'Maria Silva',
    leadPhone: '+5511999887766',
    leadScore: 45,
    leadStage: 'qualifying',
  },
  {
    id: 'demo-conv-2',
    tenantId: DEMO_TENANT_ID,
    leadId: 'demo-lead-2',
    channel: 'whatsapp',
    status: 'waiting_human',
    assignedAgentId: null,
    campaignId: null,
    aiMessagesCount: 5,
    humanMessagesCount: 0,
    leadMessagesCount: 6,
    firstResponseTimeMs: 800,
    aiModel: 'claude-sonnet-4-20250514',
    aiSummary: 'Lead insistiu em falar com atendente sobre preço especial.',
    handoffReason: 'Solicitação do lead',
    handoffAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    openedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    closedAt: null,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    leadName: 'João Santos',
    leadPhone: '+5511988776655',
    leadScore: 72,
    leadStage: 'hot',
  },
]

export const DEMO_STORAGE_KEY = 'atena:demo-dismissed'

export function isDemoDismissed(): boolean {
  return localStorage.getItem(DEMO_STORAGE_KEY) === 'true'
}

export function dismissDemo(): void {
  localStorage.setItem(DEMO_STORAGE_KEY, 'true')
}
