export type { ChannelAdapter, InboundMessage, DeliveryResult, MediaPayload, SendOptions } from './channel.interface.js'
export { MockAdapter } from './mock.adapter.js'
export type { MockMessage } from './mock.adapter.js'
export { ZApiAdapter } from './zapi.adapter.js'
export { MetaWhatsAppAdapter } from './meta-whatsapp.adapter.js'
